export interface Nutrient {
  naam: string
  afkorting?: string
  categorie: "vitamine" | "mineraal"
  adh: number
  eenheid: "mg" | "µg" | "g"
  functie: string
  bronnen: string
  tekortSymptomen: string
  oplosbaarheid?: "wateroplosbaar" | "vetoplosbaar"
}

export const nutrients: Nutrient[] = [
  {
    naam: "Vitamine A",
    afkorting: "Retinol",
    categorie: "vitamine",
    adh: 800,
    eenheid: "µg",
    functie: "Gezichtsvermogen, immuunsysteem, huid en slijmvliezen",
    bronnen: "Lever, eieren, boter, wortel, zoete aardappel, spinazie",
    tekortSymptomen: "Nachtblindheid, droge huid, verminderde weerstand",
    oplosbaarheid: "vetoplosbaar",
  },
  {
    naam: "Vitamine B1",
    afkorting: "Thiamine",
    categorie: "vitamine",
    adh: 1.1,
    eenheid: "mg",
    functie: "Energiestofwisseling, zenuwstelsel",
    bronnen: "Volkorenproducten, varkensvlees, peulvruchten",
    tekortSymptomen: "Vermoeidheid, zenuwstoornissen (beriberi)",
    oplosbaarheid: "wateroplosbaar",
  },
  {
    naam: "Vitamine B2",
    afkorting: "Riboflavine",
    categorie: "vitamine",
    adh: 1.4,
    eenheid: "mg",
    functie: "Energiestofwisseling, huid en ogen",
    bronnen: "Zuivel, eieren, volkorenproducten, groene groenten",
    tekortSymptomen: "Huidproblemen, gescheurde mondhoeken",
    oplosbaarheid: "wateroplosbaar",
  },
  {
    naam: "Vitamine B3",
    afkorting: "Niacine",
    categorie: "vitamine",
    adh: 16,
    eenheid: "mg",
    functie: "Energiestofwisseling, huid, zenuwstelsel",
    bronnen: "Vlees, vis, volkorenproducten, pinda's",
    tekortSymptomen: "Huidontsteking, vermoeidheid (pellagra)",
    oplosbaarheid: "wateroplosbaar",
  },
  {
    naam: "Vitamine B5",
    afkorting: "Pantotheenzuur",
    categorie: "vitamine",
    adh: 6,
    eenheid: "mg",
    functie: "Energiestofwisseling, hormoonproductie",
    bronnen: "Vlees, volkorenproducten, avocado, eieren",
    tekortSymptomen: "Zeldzaam; vermoeidheid, prikkelbaarheid",
    oplosbaarheid: "wateroplosbaar",
  },
  {
    naam: "Vitamine B6",
    afkorting: "Pyridoxine",
    categorie: "vitamine",
    adh: 1.4,
    eenheid: "mg",
    functie: "Eiwitstofwisseling, aanmaak rode bloedcellen",
    bronnen: "Vlees, vis, aardappelen, bananen",
    tekortSymptomen: "Huidklachten, bloedarmoede, verwardheid",
    oplosbaarheid: "wateroplosbaar",
  },
  {
    naam: "Vitamine B8",
    afkorting: "Biotine",
    categorie: "vitamine",
    adh: 50,
    eenheid: "µg",
    functie: "Vet-, koolhydraat- en eiwitstofwisseling, haar en huid",
    bronnen: "Eieren, noten, lever, volkorenproducten",
    tekortSymptomen: "Haaruitval, huidontsteking",
    oplosbaarheid: "wateroplosbaar",
  },
  {
    naam: "Vitamine B11",
    afkorting: "Foliumzuur",
    categorie: "vitamine",
    adh: 200,
    eenheid: "µg",
    functie: "Celdeling, aanmaak DNA, belangrijk bij zwangerschap",
    bronnen: "Groene bladgroenten, peulvruchten, volkorenproducten",
    tekortSymptomen: "Bloedarmoede, neurale buisdefecten bij foetus",
    oplosbaarheid: "wateroplosbaar",
  },
  {
    naam: "Vitamine B12",
    afkorting: "Cobalamine",
    categorie: "vitamine",
    adh: 2.5,
    eenheid: "µg",
    functie: "Aanmaak rode bloedcellen, zenuwstelsel",
    bronnen: "Vlees, vis, zuivel, eieren (dierlijke producten)",
    tekortSymptomen: "Bloedarmoede, vermoeidheid, zenuwschade",
    oplosbaarheid: "wateroplosbaar",
  },
  {
    naam: "Vitamine C",
    afkorting: "Ascorbinezuur",
    categorie: "vitamine",
    adh: 80,
    eenheid: "mg",
    functie: "Antioxidant, collageenvorming, ijzeropname",
    bronnen: "Citrusvruchten, paprika, aardappelen, kiwi",
    tekortSymptomen: "Vermoeidheid, tandvleesproblemen, scheurbuik",
    oplosbaarheid: "wateroplosbaar",
  },
  {
    naam: "Vitamine D",
    afkorting: "Calciferol",
    categorie: "vitamine",
    adh: 5,
    eenheid: "µg",
    functie: "Opname van calcium en fosfor, sterke botten en spieren",
    bronnen: "Zonlicht, vette vis, eieren, margarine",
    tekortSymptomen: "Botontkalking, spierzwakte, rachitis",
    oplosbaarheid: "vetoplosbaar",
  },
  {
    naam: "Vitamine E",
    afkorting: "Tocoferol",
    categorie: "vitamine",
    adh: 12,
    eenheid: "mg",
    functie: "Antioxidant, beschermt celmembranen",
    bronnen: "Plantaardige oliën, noten, zaden, avocado",
    tekortSymptomen: "Zeldzaam; zenuw- en spierproblemen",
    oplosbaarheid: "vetoplosbaar",
  },
  {
    naam: "Vitamine K",
    categorie: "vitamine",
    adh: 75,
    eenheid: "µg",
    functie: "Bloedstolling, botmineralisatie",
    bronnen: "Groene bladgroenten, broccoli, spruitjes",
    tekortSymptomen: "Verhoogde bloedingsneiging",
    oplosbaarheid: "vetoplosbaar",
  },
  {
    naam: "Calcium",
    categorie: "mineraal",
    adh: 800,
    eenheid: "mg",
    functie: "Sterke botten en tanden, spiercontractie",
    bronnen: "Zuivel, groene groenten, noten, vis met graat",
    tekortSymptomen: "Botontkalking, spierkrampen",
  },
  {
    naam: "Fosfor",
    categorie: "mineraal",
    adh: 700,
    eenheid: "mg",
    functie: "Botten en tanden, energiestofwisseling",
    bronnen: "Zuivel, vlees, vis, volkorenproducten",
    tekortSymptomen: "Zeldzaam; botproblemen, spierzwakte",
  },
  {
    naam: "Magnesium",
    categorie: "mineraal",
    adh: 375,
    eenheid: "mg",
    functie: "Spier- en zenuwfunctie, energiestofwisseling",
    bronnen: "Noten, volkorenproducten, groene groenten, peulvruchten",
    tekortSymptomen: "Spierkrampen, vermoeidheid, ritmestoornissen",
  },
  {
    naam: "Kalium",
    categorie: "mineraal",
    adh: 2000,
    eenheid: "mg",
    functie: "Vochtbalans, zenuw- en spierfunctie, bloeddruk",
    bronnen: "Groenten, fruit, aardappelen, peulvruchten",
    tekortSymptomen: "Spierzwakte, hartritmestoornissen",
  },
  {
    naam: "Natrium",
    categorie: "mineraal",
    adh: 2400,
    eenheid: "mg",
    functie: "Vochtbalans, zenuwgeleiding",
    bronnen: "Keukenzout, kant-en-klare producten, brood",
    tekortSymptomen: "Zeldzaam; meestal juist te veel inname een risico",
  },
  {
    naam: "Chloride",
    categorie: "mineraal",
    adh: 800,
    eenheid: "mg",
    functie: "Vochtbalans, maagzuurproductie",
    bronnen: "Keukenzout, kant-en-klare producten",
    tekortSymptomen: "Zeldzaam",
  },
  {
    naam: "IJzer",
    categorie: "mineraal",
    adh: 14,
    eenheid: "mg",
    functie: "Zuurstoftransport in het blood, energiestofwisseling",
    bronnen: "Rood vlees, peulvruchten, volkorenproducten, groene groenten",
    tekortSymptomen: "Bloedarmoede, vermoeidheid, bleekheid",
  },
  {
    naam: "Zink",
    categorie: "mineraal",
    adh: 10,
    eenheid: "mg",
    functie: "Immuunsysteem, wondgenezing, celdeling",
    bronnen: "Vlees, schaal- en schelpdieren, peulvruchten, noten",
    tekortSymptomen: "Verminderde weerstand, huidproblemen",
  },
  {
    naam: "Koper",
    categorie: "mineraal",
    adh: 1,
    eenheid: "mg",
    functie: "Aanmaak bindweefsel en rode bloedcellen",
    bronnen: "Lever, schaaldieren, noten, volkorenproducten",
    tekortSymptomen: "Zeldzaam; bloedarmoede",
  },
  {
    naam: "Mangaan",
    categorie: "mineraal",
    adh: 2,
    eenheid: "mg",
    functie: "Botvorming, stofwisseling, antioxidant",
    bronnen: "Volkorenproducten, noten, thee, groene groenten",
    tekortSymptomen: "Zeer zeldzaam",
  },
  {
    naam: "Selenium",
    categorie: "mineraal",
    adh: 55,
    eenheid: "µg",
    functie: "Antioxidant, schildklierfunctie, immuunsysteem",
    bronnen: "Vis, noten (paranoten), vlees, volkorenproducten",
    tekortSymptomen: "Verminderde weerstand, spierklachten",
  },
  {
    naam: "Jodium",
    categorie: "mineraal",
    adh: 150,
    eenheid: "µg",
    functie: "Aanmaak schildklierhormonen",
    bronnen: "Jodiumhoudend zout, vis, zuivel",
    tekortSymptomen: "Schildklierproblemen, struma",
  },
  {
    naam: "Chroom",
    categorie: "mineraal",
    adh: 40,
    eenheid: "µg",
    functie: "Regulatie van bloedsuikerspiegel",
    bronnen: "Volkorenproducten, noten, broccoli, vlees",
    tekortSymptomen: "Zeer zeldzaam",
  },
  {
    naam: "Molybdeen",
    categorie: "mineraal",
    adh: 50,
    eenheid: "µg",
    functie: "Enzymfunctie, afbraak van aminozuren",
    bronnen: "Peulvruchten, volkorenproducten, noten",
    tekortSymptomen: "Zeer zeldzaam",
  },
  {
    naam: "Fluoride",
    categorie: "mineraal",
    adh: 3.5,
    eenheid: "mg",
    functie: "Sterke tanden, weerstand tegen cariës",
    bronnen: "Drinkwater, thee, fluoridetandpasta",
    tekortSymptomen: "Verhoogd risico op tandcariës",
  },
]

export const categorieLabels: Record<Nutrient["categorie"], string> = {
  vitamine: "Vitaminen",
  mineraal: "Mineralen",
}
